Repository Programmers-FE5-VueFinder/bookjeokbookjeok, pull requests merged in 2025-06, with the labels that each got.

#1 ✨feature: 페이지 라우팅 설정
  src/App.tsx
  src/pages/CreatePost.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/NotFound.tsx
  src/pages/PostDetail.tsx
  src/pages/PostList.tsx
  src/pages/Profile.tsx
  src/pages/SearchResult.tsx
  src/routes/index.tsx
  src/routes/layouts/ChannelLayout.tsx
  src/routes/layouts/RootLayout.tsx
Labels: ⭐ Feature

#2 💄Style: 게시글 카드 컴포넌트
  package.json
  src/components/common/BookCard.tsx
  src/css/font.css
  src/css/index.css
  src/pages/Profile.tsx
Labels: 💅 Style

#4 Feature/apis
  package.json
  src/apis/auth.ts
  src/apis/index.ts
  src/apis/post.ts
  src/types/supabase.ts
Labels: ⭐ Feature

#5 Feature/프로필 설정 모달 & 헤더 크기 반응형
  src/apis/post.ts
  src/components/common/BookCard.tsx
  src/components/component/MyPage/SettingModal.tsx
  src/css/index.css
  src/pages/Login.tsx
  src/pages/Notification.tsx
  src/pages/PostList.tsx
  src/pages/Profile.tsx
  src/routes/layouts/Footer.tsx
  src/routes/layouts/Header.tsx
  src/store/authStore.ts
Labels: ⭐ Feature, 💅 Style

#9 Feature/write post
  package.json
  src/components/component/write-post/ReactQuillEditor.tsx
  src/components/component/write-post/WritePost.tsx
  src/components/component/write-post/quillAttribute.ts
  src/css/index.css
  src/css/reactQuillCustom.css
  src/pages/CreatePost.tsx
  src/routes/index.tsx
Labels: ⭐ Feature

#11 [Update] Feature/book club
  src/components/component/MyPage/ProfileImg.tsx
  src/components/component/MyPage/SettingModal.tsx
  src/css/index.css
  src/css/root.css
  src/pages/BookClub.tsx
  src/pages/Profile.tsx
  src/routes/index.tsx
  src/store/profileStore.ts
  src/types/supabase.ts
Labels: ⭐ Feature, 💅 Style

#17 fix/Channel gnb 채널 경로 수정
  src/apis/post.ts
  src/components/common/BookCard.tsx
  src/components/common/Header.tsx
  src/pages/Login.tsx
  src/pages/PostList.tsx
  src/routes/layouts/ChannelLayout.tsx
  src/types/type.d.ts
  src/utils/supabase.ts
Labels: 🪲 Bug

#21 Feature/Channel 다이어리 채널 api 연동 및 css 수정
  src/apis/post.ts
  src/components/common/BookCard.tsx
  src/pages/PostList.tsx
  src/types/type.d.ts
Labels: ⭐ Feature, 💅 Style

#23 Feature/book-detail
  package.json
  src/App.tsx
  src/apis/add-book-if-not-exists.ts
  src/apis/book-review.ts
  src/apis/book-search.ts
  src/apis/bookmark.ts
  src/apis/post.ts
  src/components/component/book-detail/BookPage.tsx
  src/components/component/book-detail/Test.tsx
  src/components/component/book-detail/content/RelatedContentItem.tsx
  src/components/component/book-detail/content/RelatedContentSkeleton.tsx
  src/components/component/book-detail/content/RelatedContents.tsx
  src/components/component/book-detail/post/BookPost.tsx
  src/components/component/book-detail/post/BookPostItem.tsx
  src/components/component/book-detail/post/BookPostSkeleton.tsx
  src/components/component/book-detail/review/BookReviewSkeleton.tsx
  src/components/component/book-detail/review/OneLineReview.tsx
  src/components/component/book-detail/review/ReviewInput.tsx
  src/components/component/book-detail/review/ReviewItem.tsx
  src/css/index.css
  src/hooks/use-infinite-scroll.ts
  src/types/book.ts
  src/types/post.ts
  src/types/supabase.ts
  src/utils/format-author.ts
  src/utils/format-time.ts
Labels: 🛠️ Refactoring, ⭐ Feature

#28 Feature/book club
  package.json
  src/apis/book-club.ts
  src/components/common/UserCard.tsx
  src/components/component/chat-room/ChatBubble.tsx
  src/components/component/chat-room/ChatBubbleGroup.tsx
  src/components/component/chat-room/ChatContent.tsx
  src/components/component/chat-room/ChatHeader.tsx
  src/components/component/chat-room/ChatInput.tsx
  src/components/component/chat-room/ChatModal.tsx
  src/components/component/write-post/WritePost.tsx
  src/pages/BookClub.tsx
  src/pages/BookClubChat.tsx
  src/routes/index.tsx
  src/types/global.d.ts
  src/types/supabase.ts
Labels: ⭐ Feature, 💅 Style

#30 Feature/sign up
  package.json
  src/components/common/Header.tsx
  src/components/common/SignUpModal.tsx
  src/components/component/write-post/BookHTML.tsx
  src/components/component/write-post/BookRating.tsx
  src/components/component/write-post/CategorySelect.tsx
  src/components/component/write-post/ReactQuillEditor.tsx
  src/components/component/write-post/WritePost.tsx
  src/css/reactQuillCustom.css
  src/pages/CreatePost.tsx
  src/pages/SignUp.tsx
Labels: 🛠️ Refactoring

#36 Feature/write-post
  src/App.tsx
  src/apis/auth.ts
  src/apis/post.ts
  src/components/common/Toastfy.tsx
  src/components/component/BookSearchModal.tsx
  src/components/component/write-post/BookRating.tsx
  src/components/component/write-post/CategorySelect.tsx
  src/components/component/write-post/CustomToolBar.tsx
  src/components/component/write-post/ReactQuillEditor.tsx
  src/components/component/write-post/SelectBookInfo.tsx
  src/components/component/write-post/WritePost.tsx
  src/components/component/write-post/customBlot.ts
  src/components/component/write-post/customEmbed.ts
  src/components/component/write-post/quillAttribute.ts
  src/components/component/write-post/quillOverride.ts
  src/css/reactQuillCustom.css
  src/routes/index.tsx
  src/utils/authStoreSessionUpdate.ts
Labels: 🪲 Bug, 🛠️ Refactoring

#37 Feature/mypage - 기본 이미지 적용, 닉네임 유효성, 중복 검사, 도서 정보 불러오기 로직 수정
  src/assets/images/default_post_img.png
  src/components/common/BookCard.tsx
  src/components/common/UserCard.tsx
  src/components/component/MyPage/BookClubArea.tsx
  src/components/component/MyPage/BookMarkArea.tsx
  src/components/component/MyPage/BookMarkCard.tsx
  src/components/component/MyPage/DiaryArea.tsx
  src/components/component/MyPage/ProfileImg.tsx
  src/components/component/MyPage/SettingModal.tsx
  src/components/component/chat-room/ChatBubbleGroup.tsx
  src/pages/Profile.tsx
  src/types/book.ts
Labels: ⭐ Feature, 💅 Style

#38 Feature/alarm
  src/apis/notification.ts
  src/components/common/AlarmModal.tsx
  src/components/common/Header.tsx
  src/components/component/alarm/AlarmList.tsx
  src/components/component/alarm/AlarmModal.tsx
  src/pages/Notification.tsx
  src/routes/index.tsx
  src/types/global.d.ts
  src/types/supabase.ts
Labels: ⭐ Feature, 💅 Style

#40 Feature/post-detail
  src/components/common/CheckModal.tsx
  src/components/component/post-detail/Comment.tsx
  src/components/component/post-detail/CommentInput.tsx
  src/components/component/post-detail/DetailBookInfo.tsx
  src/components/component/post-detail/EditSelectBox.tsx
  src/components/component/post-detail/FollowButton.tsx
  src/components/component/post-detail/PostHeader.tsx
  src/components/component/post-detail/PostProfile.tsx
  src/components/component/write-post/ReactQuillEditor.tsx
  src/components/component/write-post/WritePost.tsx
  src/pages/EditPost.tsx
  src/pages/PostDetail.tsx
  src/routes/index.tsx
  src/types/post.ts
Labels: ⭐ Feature, 💅 Style

#44 Fix/Channel: 채널 카드 목록 - BookCard 컴포넌트 적용 및 스타일 수정
  src/components/common/BookCard.tsx
  src/pages/PostList.tsx
  src/types/type.d.ts
Labels: 🛠️ Refactoring, ⭐ Feature, 💅 Style

#45 Feature/post-detail
  src/apis/post.ts
  src/components/common/CheckModal.tsx
  src/components/component/MyPage/ProfileImg.tsx
  src/components/component/post-detail/CommentInput.tsx
  src/components/component/post-detail/EditSelectBox.tsx
  src/components/component/post-detail/FollowButton.tsx
  src/components/component/post-detail/Like.tsx
  src/components/component/post-detail/PostHeader.tsx
  src/components/component/post-detail/PostProfile.tsx
  src/pages/PostDetail.tsx
Labels: ⭐ Feature, 💅 Style

#48 Feature/book-detail: 버그 수정 및 클릭 시 페이지 이동
  src/apis/book-review.ts
  src/apis/comment.ts
  src/apis/post.ts
  src/components/component/book-detail/BookPage.tsx
  src/components/component/book-detail/post/BookPost.tsx
  src/components/component/book-detail/post/BookPostItem.tsx
  src/components/component/book-detail/review/OneLineReview.tsx
  src/components/component/book-detail/review/ReviewItem.tsx
  src/types/book.ts
  src/types/post.ts
Labels: 🪲 Bug, ⭐ Feature

#43 Feature/mypage - 다른 유저 프로필 마이 북클럽 탭 감추기, follow.ts 생성
  src/apis/follow.ts
  src/components/component/MyPage/BookClubArea.tsx
  src/components/component/MyPage/BookMarkArea.tsx
  src/components/component/MyPage/BookMarkCard.tsx
  src/components/component/MyPage/SettingModal.tsx
  src/pages/Profile.tsx
Labels: 💅 Style

#46 Feature/comment: 댓글, 답글 기능
  src/apis/comment.ts
  src/apis/notification.ts
  src/components/component/post-detail/Comment.tsx
  src/components/component/post-detail/CommentInput.tsx
  src/components/component/post-detail/comments/Comment.tsx
  src/components/component/post-detail/comments/CommentInput.tsx
  src/pages/PostDetail.tsx
  src/types/supabase.ts
  src/types/type.d.ts
  src/utils/format-time.ts
Labels: ⭐ Feature

#47 Feature/search-result: 게시물 목록 검색
  src/components/common/UserCard.tsx
  src/pages/SearchResult.tsx
Labels: ⭐ Feature, 💅 Style

#53 ✨ feat: 도서 검색 시 검색 결과가 없는 경우 문구 보여주게 변경
  src/components/component/BookSearchModal.tsx
Labels: ⭐ Feature

#58 ✨ feat: 좋아요, 댓글 갯수 카드 컴포넌트에 표시
  src/apis/following-posts.ts
  src/apis/user.ts
  src/components/common/BookCard.tsx
  src/components/common/UserCardSkeleton.tsx
  src/components/component/Home/BestsellerSlider.tsx
  src/components/component/Home/PopularDiaryCard.tsx
  src/components/component/Home/PopularDiaryCardSkeleton.tsx
  src/components/component/MyPage/BookClubArea.tsx
  src/components/component/MyPage/BookMarkArea.tsx
  src/components/component/MyPage/CommunityArea.tsx
  src/components/component/MyPage/DiaryArea.tsx
  src/components/component/MyPage/ProfileImg.tsx
  src/components/component/MyPage/SettingModal.tsx
  src/pages/Home.tsx
  src/pages/Profile.tsx
  src/pages/SearchResult.tsx
Labels: ⭐ Feature, 💅 Style

#59 Feature/book-detail: 버그 수정 및 경로 수정
  src/components/component/book-detail/BookPage.tsx
  src/components/component/book-detail/post/BookPost.tsx
  src/components/component/book-detail/post/BookPostItem.tsx
  src/components/component/book-detail/review/OneLineReview.tsx
  src/components/component/book-detail/review/ReviewItem.tsx
Labels: 🪲 Bug, ⭐ Feature

#60 Feature/channel: 최종 수정
  src/apis/following-posts.ts
  src/apis/post.ts
  src/components/common/BookCard.tsx
  src/components/component/post-detail/PostHeader.tsx
  src/pages/PostDetail.tsx
  src/pages/PostList.tsx
Labels: 🪲 Bug

#62 Feature/post-detail
  src/apis/follow.ts
  src/apis/post.ts
  src/components/component/post-detail/DiarySelectBook.tsx
  src/components/component/post-detail/FollowButton.tsx
  src/components/component/post-detail/PostHeader.tsx
  src/components/component/post-detail/PostProfile.tsx
  src/components/component/write-post/ReactQuillEditor.tsx
  src/components/component/write-post/WritePost.tsx
  src/pages/EditPost.tsx
  src/pages/PostDetail.tsx
Labels: 🛠️ Refactoring, ⭐ Feature

#63 feature/Home: 인기 다이어리 line-clamp 적용 및 상세 페이지 경로 수정
  src/components/component/Home/PopularDiaryCard.tsx
Labels: 🛠️ Refactoring, 💅 Style

#66 ✨ feat: 포스트 내용에서 태그 삭제 및 html 엔티 문자로 디코딩
  src/components/component/book-detail/post/BookPostItem.tsx
Labels: ⭐ Feature

#70 feature/search-result 검색 페이지 게시물 상세페이지 이동 경로 수정
  src/pages/SearchResult.tsx
Labels: 🪲 Bug

#68 Feature/post-detail
  src/apis/post.ts
  src/components/common/CheckModal.tsx
  src/components/common/Header.tsx
  src/components/component/post-detail/DiarySelectBook.tsx
  src/components/component/post-detail/EditSelectBox.tsx
  src/components/component/post-detail/PostHeader.tsx
  src/components/component/write-post/BookRating.tsx
  src/components/component/write-post/CategorySelect.tsx
  src/components/component/write-post/ReactQuillEditor.tsx
  src/components/component/write-post/WritePost.tsx
  src/css/reactQuillCustom.css
  src/pages/PostDetail.tsx
  src/routes/index.tsx
Labels: ⭐ Feature

#72 ✨ feat: 비로그인으로 댓글, 답글 입력 시 토스트 메시지 표시
  src/components/component/post-detail/comments/Comment.tsx
  src/components/component/post-detail/comments/CommentInput.tsx
Labels: ⭐ Feature

#75 feature/Channel: 디버깅 콘솔로그 코드 삭제
  src/assets/images/main_logo.png
  src/components/common/Header.tsx
  src/constants/mainBannerSlide.ts
  src/pages/Home.tsx
  src/pages/PostList.tsx
Labels: 🪲 Bug, 💩 Poop
